FROM alpine:3.24

ARG MIST_OPTS=""
ARG MIST_DEBUG=3
ENV MIST_VERSION=3.11.1
ENV MIST_SHA256=8a76b9cc06fcaf544a4d80763234a1b0001d34ea96e414c148e90fbb37d091d6

ENV MBEDTLS_VERSION=3.6.6
ENV MBEDTLS_SHA256=8fb65fae8dcae5840f793c0a334860a411f884cc537ea290ce1c52bb64ca007a

RUN set -eux; \
  apk add --no-cache --virtual .build-deps \
    git \
    patch \
    meson \
    ninja \
    gcc \
    g++ \
    linux-headers \
    pigz \
    curl \
    cjson-dev \
    pkgconfig \
    pax-utils; \
  \
  curl -fsSL -o /tmp/src.tar.gz "https://r.mistserver.org/dl/mistserver_sourceV${MIST_VERSION}.tar.gz"; \
  echo "${MIST_SHA256} */tmp/src.tar.gz" | sha256sum -c -; \
  mkdir /src; \
  tar -xzf /tmp/src.tar.gz -C /src; \
  rm -f /tmp/src.tar.gz; \
  \
# Explicitly build mbedtls because official builds lack DTLS support
  mkdir -p /deps/build/mbedtls; \
  curl -fsSL -o /tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2 "https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${MBEDTLS_VERSION}/mbedtls-${MBEDTLS_VERSION}.tar.bz2"; \
  echo "${MBEDTLS_SHA256} */tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2" | sha256sum -c -; \
  tar -xjf /tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2 -C /deps; \
  rm -f /tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2; \
  \
  cp /src/subprojects/packagefiles/mbedtls/meson.build /deps/mbedtls-${MBEDTLS_VERSION}/; \
  cp /src/subprojects/packagefiles/mbedtls/include/mbedtls/mbedtls_config.h /deps/mbedtls-${MBEDTLS_VERSION}/include/mbedtls/; \
  \
  cd /deps/build/mbedtls; \
  meson setup /deps/mbedtls-${MBEDTLS_VERSION} -Dstrip=true; \
  meson install; \
  \
  mkdir /build; \
  cd /build; \
  meson setup /src \
    -DDOCKERRUN=true \
    -DNOUPDATE=true \
    -DDEBUG=${MIST_DEBUG} \
    -DVERSION=${MIST_VERSION} \
    -DRELEASE="Docker_$(apk --print-arch)" \
    -Dstrip=true \
    ${MIST_OPTS:-}; \
  ninja install; \
  \
  runDeps="$( \
    scanelf --needed --nobanner --format '%n' --recursive /usr/local \
      | tr ',' '\n' \
      | sort -u \
      | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
  )"; \
  apk add --no-cache --virtual .mist-rundeps $runDeps; \
  apk del .build-deps

EXPOSE 4242 8080 1935 5554 8889/udp 18203/udp

ENTRYPOINT ["MistController"]
