FROM alpine:3.23

ARG MIST_OPTS=""
ARG MIST_DEBUG=3
ENV MIST_VERSION=3.9.2
ENV MBEDTLS_VERSION=3.6.5

RUN set -eux; \
  apk add --no-cache --virtual .build-deps \
    git \
    patch \
    meson \
    ninja \
    gcc \
    g++ \
    linux-headers \
    pigz \
    curl \
    cjson-dev \
    pkgconfig \
    pax-utils; \
  \
  curl -fsSL -o /tmp/src.tar.gz "https://github.com/DDVTECH/mistserver/archive/refs/tags/${MIST_VERSION}.tar.gz"; \
  mkdir /src; \
  tar -xzf /tmp/src.tar.gz --strip-components=1 -C /src; \
  rm -f /tmp/src.tar.gz; \
  \
# Explicitly build mbedtls because official builds lack DTLS support
  mkdir -p /deps/build/mbedtls; \
  curl -fsSL -o /tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2 "https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${MBEDTLS_VERSION}/mbedtls-${MBEDTLS_VERSION}.tar.bz2"; \
  tar -xjf /tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2 -C /deps; \
  rm -f /tmp/mbedtls-${MBEDTLS_VERSION}.tar.bz2; \
  \
  cp /src/subprojects/packagefiles/mbedtls/meson.build /deps/mbedtls-${MBEDTLS_VERSION}/; \
  cp /src/subprojects/packagefiles/mbedtls/include/mbedtls/mbedtls_config.h /deps/mbedtls-${MBEDTLS_VERSION}/include/mbedtls/; \
  \
  cd /deps/build/mbedtls; \
  meson setup /deps/mbedtls-${MBEDTLS_VERSION} -Dstrip=true; \
  meson install; \
  \
  mkdir /build; \
  cd /build; \
  meson setup /src \
    -DDOCKERRUN=true \
    -DNOUPDATE=true \
    -DDEBUG=${MIST_DEBUG} \
    -DVERSION=${MIST_VERSION} \
    -DRELEASE="Docker_$(apk --print-arch)" \
    -Dstrip=true \
    ${MIST_OPTS:-}; \
  ninja install; \
  \
  runDeps="$( \
    scanelf --needed --nobanner --format '%n' --recursive /usr/local \
      | tr ',' '\n' \
      | sort -u \
      | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
  )"; \
  apk add --no-cache --virtual .mist-rundeps $runDeps; \
  apk del .build-deps

EXPOSE 4242 8080 1935 5554 8889/udp 18203/udp

ENTRYPOINT ["MistController"]
